"""add missing columns

Revision ID: 6c6fd8c9040c
Revises: 
Create Date: 2026-04-12 07:31:31.442869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c6fd8c9040c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.alter_column('messages', 'message_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('text', 'link', 'code', name='message_type_enum', create_constraint=True),
               nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_room_id'), 'messages', ['room_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='SET NULL')
    op.drop_column('messages', 'sender')
    op.alter_column('resources', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('resources', 'resource_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('video', 'pdf', 'link', 'note', 'pyq', name='resource_type_enum', create_constraint=True),
               existing_nullable=False)
    op.alter_column('resources', 'link',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_resources_added_by'), 'resources', ['added_by'], unique=False)
    op.create_index(op.f('ix_resources_room_id'), 'resources', ['room_id'], unique=False)
    op.create_foreign_key(None, 'resources', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'resources', 'users', ['added_by'], ['id'], ondelete='SET NULL')
    op.drop_column('resources', 'creator_id')
    op.drop_column('resources', 'url')
    op.drop_column('resources', 'tag')
    op.drop_column('resources', 'source_name')
    op.drop_column('resources', 'type')
    op.add_column('rooms', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('rooms', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('rooms', sa.Column('is_live', sa.Boolean(), nullable=False))
    op.add_column('rooms', sa.Column('focus', sa.Integer(), nullable=False))
    op.add_column('rooms', sa.Column('max_members', sa.Integer(), nullable=False))
    op.add_column('rooms', sa.Column('meeting_link', sa.String(length=512), nullable=True))
    op.add_column('rooms', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('rooms', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('rooms', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.create_index(op.f('ix_rooms_owner_id'), 'rooms', ['owner_id'], unique=False)
    op.create_index(op.f('ix_rooms_title'), 'rooms', ['title'], unique=False)
    op.create_foreign_key(None, 'rooms', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('rooms', 'tag')
    op.drop_column('rooms', 'name')
    op.drop_column('rooms', 'created_by')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('users', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'xp',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('users', 'streak')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('streak', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'xp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('rooms', sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('tag', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_index(op.f('ix_rooms_title'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_owner_id'), table_name='rooms')
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=True)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.alter_column('rooms', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rooms', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('rooms', 'updated_at')
    op.drop_column('rooms', 'meeting_link')
    op.drop_column('rooms', 'max_members')
    op.drop_column('rooms', 'focus')
    op.drop_column('rooms', 'is_live')
    op.drop_column('rooms', 'owner_id')
    op.drop_column('rooms', 'tags')
    op.add_column('resources', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('resources', sa.Column('source_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('resources', sa.Column('tag', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('resources', sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('resources', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_index(op.f('ix_resources_room_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_added_by'), table_name='resources')
    op.alter_column('resources', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('resources', 'link',
               existing_type=sa.String(length=1024),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('resources', 'resource_type',
               existing_type=sa.Enum('video', 'pdf', 'link', 'note', 'pyq', name='resource_type_enum', create_constraint=True),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('resources', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('messages', sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_room_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'message_type',
               existing_type=sa.Enum('text', 'link', 'code', name='message_type_enum', create_constraint=True),
               type_=sa.VARCHAR(),
               nullable=True)
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('posts_pkey'))
    )
    # ### end Alembic commands ###
